document.write( '<!DOCTYPE html>\n' );
document.write( '<html lang=\"en\" >\n' );
document.write( '<head>\n' );
document.write( '  <meta charset=\"UTF-8\">\n' );
document.write( '  <title>antaira bootstrap 4</title>\n' );
document.write( '  <meta charset=\"UTF-8\">\n' );
document.write( '  <meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">\n' );
document.write( '  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\n' );
document.write( '  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css\">\n' );
document.write( '  <link rel=\"stylesheet\" href=\"./scss/navbar.css\">\n' );
document.write( '</head>\n' );
document.write( '<body>\n' );
document.write( '<!-- logo -->\n' );
document.write( '<div class=\"logoTitle\">\n' );
document.write( '    <div class=\"logo-img\">\n' );
document.write( '        <img src=\"./img/antaira-logo.png\" alt=\"#\">\n' );
document.write( '    </div>\n' );
document.write( '    <div class=\"info\">\n' );
document.write( '        <p>Firmware:\n' );
document.write( '         <a href=\"#\" onclick=\"window.open(\'https://www.antaira.com/\', \'googleapis\', config=\'height=500,width=500\');\">Antaira r49432 (07/07/22)</a>\n' );
document.write( '         <br>Time:\n' );
document.write( '         <br>WAN IP:\n' );
document.write( '        </p>\n' );
document.write( '    </div>\n' );
document.write( '    <button class=\"navbar-toggler\" type=\"button\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n' );
document.write( '        <i class=\"fas fa-bars text-white\"></i>\n' );
document.write( '    </button>\n' );
document.write( '</div>\n' );
document.write( '<!-- 上層 Navbar -->\n' );
document.write( '<nav class=\"navbar navbar-expand-custom navbar-mainbg\">\n' );
document.write( '    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n' );
document.write( '        <ul class=\"navbar-nav ml\">\n' );
document.write( '            <div class=\"hori-selector\">\n' );
document.write( '                <div class=\"left\"></div>\n' );
document.write( '                <div class=\"right\"></div>\n' );
document.write( '            </div>\n' );
document.write( '            <li class=\"nav-item active\">\n' );
document.write( '                <a class=\"nav-link\" href=\"./Setup.html\" data-target=\"setup\" onclick=\"event.preventDefault();\">Setup</a>\n' );
document.write( '                <!-- <a class=\"nav-link\" href=\"javascript:void(0);\" data-target=\"setup\">Setup</a> -->\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"./Wireless-Basic Settings.html\" data-target=\"wireless\" onclick=\"event.preventDefault();\">Wireless</a>\n' );
document.write( '                <!-- <a class=\"nav-link\" href=\"javascript:void(0);\" data-target=\"wireless\">Wireless</a> -->\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"javascript:void(0);\" data-target=\"services\">Services</a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"javascript:void(0);\" data-target=\"security\">Security</a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"javascript:void(0);\" data-target=\"access-restrictions\">Access Restrictions</a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"javascript:void(0);\" data-target=\"port-forwarding\">Port Forwarding</a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"javascript:void(0);\" data-target=\"administration\">Administration</a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"javascript:void(0);\" data-target=\"status\">Status</a>\n' );
document.write( '            </li>\n' );
document.write( '        </ul>\n' );
document.write( '    </div>\n' );
document.write( '</nav>\n' );
document.write( '\n' );
document.write( '<!-- Setup 下層 Navbar -->\n' );
document.write( '<div id=\"setupNavbar\" style=\"display:block;\">\n' );
document.write( '    <nav class=\"navbar-expand-lg bg-body-tertiary\">\n' );
document.write( '        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n' );
document.write( '            <ul class=\"navbar-nav\">\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link active\" aria-current=\"page\" href=\"./Setup.html\" data-target=\"basic-setup\">Basic Setup</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Setup-ipv6.html\" data-target=\"ipv6\">IPv6</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Setup-DDNS.html\" data-target=\"ddns\">DDNS</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Setup-MACAddressClone.HTML\" data-target=\"mac-address-clone\">MAC Address Clone</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Setup-AdvancedRouting.html\" data-target=\"advanced-routing\">Advanced Routing</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Setup-Networking.html\" data-target=\"networking\">Networking</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Setup-Tunnels.html\" data-target=\"tunnels\">Tunnels</a>\n' );
document.write( '                </li>\n' );
document.write( '            </ul>\n' );
document.write( '        </div>\n' );
document.write( '    </nav>\n' );
document.write( '</div>\n' );
document.write( '\n' );
document.write( '<!-- Wireless 下層 Navbar -->\n' );
document.write( '<div id=\"wirelessNavbar\" style=\"display:none;\">\n' );
document.write( '    <nav class=\"navbar-expand-lg bg-body-tertiary\">\n' );
document.write( '        <div class=\"collapse navbar-collapse\" id=\"wirelessNav\">\n' );
document.write( '            <ul class=\"navbar-nav\">\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link active\" aria-current=\"page\" href=\"./Wireless-Basic Settings.html\" data-target=\"basicSettings\">Basic Settings</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Wireless-Wireless Security.html\" data-target=\"wireless-security\">Wireless Security</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Wireless-MAC Filter.html\" data-target=\"mac-filter\">MAC Filter</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Wireless-wlan0-WDS.html\" data-target=\"wlan0-WDS\">wlan0-WDS</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Wireless-wlan1-WDS.html\" data-target=\"wlan1-WDS\">wlan1-WDS</a>\n' );
document.write( '                </li>\n' );
document.write( '            </ul>\n' );
document.write( '        </div>\n' );
document.write( '    </nav>\n' );
document.write( '</div>\n' );
document.write( '\n' );
document.write( '<!-- Services 下層 Navbar -->\n' );
document.write( '<div id=\"servicesNavbar\" style=\"display:none;\">\n' );
document.write( '    <nav class=\"navbar-expand-lg bg-body-tertiary\">\n' );
document.write( '        <div class=\"collapse navbar-collapse\" id=\"servicesNav\">\n' );
document.write( '            <ul class=\"navbar-nav\">\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link active\" aria-current=\"page\" href=\"./Services.html\" data-target=\"services\">Services</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Services-FreeRADIUS.html\" data-target=\"freeradius\">FreeRADIUS</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Services-PPPoE Server.html\" data-target=\"pppoe-server\">PPPoE Server</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Services-vpn.html\" data-target=\"vpn\">VPN </a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Services-USB.html\" data-target=\"usb\">USB</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Services-NAS.html\" data-target=\"nas\">NAS</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Services-Hotspot.html\" data-target=\"hotspot\">Hotspot</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Services-Ad Blocking.html\" data-target=\"adBlocking\">Ad Blocking</a>\n' );
document.write( '                </li>\n' );
document.write( '            </ul>\n' );
document.write( '        </div>\n' );
document.write( '    </nav>\n' );
document.write( '</div>\n' );
document.write( '\n' );
document.write( '<!-- Security 下層 Navbar (未改選項) -->\n' );
document.write( '<div id=\"securityNavbar\" style=\"display:none;\">\n' );
document.write( '    <nav class=\"navbar-expand-lg bg-body-tertiary\">\n' );
document.write( '        <div class=\"collapse navbar-collapse\" id=\"securityNav\">\n' );
document.write( '            <ul class=\"navbar-nav\">\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link active\" aria-current=\"page\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"> </a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '            </ul>\n' );
document.write( '        </div>\n' );
document.write( '    </nav>\n' );
document.write( '</div>\n' );
document.write( '\n' );
document.write( '<!-- Access Restrictions 下層 Navbar (未改選項) -->\n' );
document.write( '<div id=\"access-restrictionsNavbar\" style=\"display:none;\">\n' );
document.write( '    <nav class=\"navbar-expand-lg bg-body-tertiary\">\n' );
document.write( '        <div class=\"collapse navbar-collapse\" id=\"access-restrictionsNav\">\n' );
document.write( '            <ul class=\"navbar-nav\">\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link active\" aria-current=\"page\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"> </a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '            </ul>\n' );
document.write( '        </div>\n' );
document.write( '    </nav>\n' );
document.write( '</div>\n' );
document.write( '\n' );
document.write( '<!-- Port Forwarding 下層 Navbar (未改選項) -->\n' );
document.write( '<div id=\"port-forwardingNavbar\" style=\"display:none;\">\n' );
document.write( '    <nav class=\"navbar-expand-lg bg-body-tertiary\">\n' );
document.write( '        <div class=\"collapse navbar-collapse\" id=\"port-forwardingNav\">\n' );
document.write( '            <ul class=\"navbar-nav\">\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link active\" aria-current=\"page\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"> </a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"#\"></a>\n' );
document.write( '                </li>\n' );
document.write( '            </ul>\n' );
document.write( '        </div>\n' );
document.write( '    </nav>\n' );
document.write( '</div>\n' );
document.write( '\n' );
document.write( '<!-- Administration 下層 Navbar -->\n' );
document.write( '<div id=\"administrationNavbar\" style=\"display:none;\">\n' );
document.write( '    <nav class=\"navbar-expand-lg bg-body-tertiary\">\n' );
document.write( '        <div class=\"collapse navbar-collapse\" id=\"administrationNav\">\n' );
document.write( '            <ul class=\"navbar-nav\">\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link active\" aria-current=\"page\" href=\"./Administration-Management.html\" data-target=\"management\">Management</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Administration-Keep Alive.html\" data-target=\"keep-alive\">Keep Alive</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Administration-Sysctl.html\" data-target=\"sysctl\">Sysctl</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Administration-Commands.html\" data-target=\"commands\">Commands</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Administration-WOL.html\" data-target=\"wol\">WOL</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Administration-Factory Defaults.html\" data-target=\"factory-defaults\">Factory Defaults</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Administration-Firmware Upgrade.html\" data-target=\"firmware-upgrade\">Firmware Upgrade</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Administration-Backup.html\" data-target=\"backup\">Backup</a>\n' );
document.write( '                </li>\n' );
document.write( '            </ul>\n' );
document.write( '        </div>\n' );
document.write( '    </nav>\n' );
document.write( '</div>\n' );
document.write( '\n' );
document.write( '<!-- Status 下層 Navbar -->\n' );
document.write( '<div id=\"statusNavbar\" style=\"display:none;\">\n' );
document.write( '    <nav class=\"navbar-expand-lg bg-body-tertiary\">\n' );
document.write( '        <div class=\"collapse navbar-collapse\" id=\"statusNav\">\n' );
document.write( '            <ul class=\"navbar-nav\">\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link active\" aria-current=\"page\" href=\"./Status-Router.html\" data-target=\"router\">Router</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Status-WAN.html\" data-target=\"wan\">WAN</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Status-lan.html\" data-target=\"lan\">LAN</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Status-Wireless.html\" data-target=\"status-wireless\">Wireless</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"bandwidth\">Bandwidth</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"./Status-Syslog.html\" data-target=\"syslog\">Syslog</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"#\" data-target=\"sys-info\">Sys Info</a>\n' );
document.write( '                </li>\n' );
document.write( '            </ul>\n' );
document.write( '        </div>\n' );
document.write( '    </nav>\n' );
document.write( '</div>\n' );
document.write( '\n' );
document.write( '  <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\n' );
document.write( '  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\n' );
document.write( '  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js\"></script>\n' );
document.write( '  <script  src=\"./script.js\"></script>\n' );
document.write( '</body>\n' );
document.write( '</html>\n' );
